version: '3'
services:
  api:
    image: kegtron-v1-api-proxy:dev
    expose:
      - 5000
    ports:
      - 5000:5000
    stdin_open: true
    environment:
      # KENGTRON_PROXY_LOG_LEVEL: DEBUG
      KEGTRON_PROXY_ROLE: "api"
      TZ: America/New_York
    tty: true
  scanner:
    image: kegtron-v1-api-proxy:dev
    depends_on:
      - api
    network_mode: host
    privileged: true
    environment:
      # KENGTRON_SCANNER_LOG_LEVEL: DEBUG
      KEGTRON_PROXY_ROLE: "scanner"
      TZ: America/New_York
    tty: true
      