version: '3'
services:
  nginx: 
    image : nginx:latest 
    expose: 
      - 80
      - 443
    ports:
      - 80:80
      - 443:443
    environment:
      TZ: America/New_York
    volumes:  
      - ./nginx.conf:/etc/nginx/conf.d/nginx.conf
      - ./certs/localhost.crt:/etc/nginx/certs/localhost.crt
      - ./certs/localhost.key:/etc/nginx/certs/localhost.key
    depends_on:
      - api
  api:
    image: kegtron-v1-api-proxy:dev
    expose:
      - 5000
    stdin_open: true
    environment:
      KEGTRON_PROXY_ROLE: "api"
      TZ: America/New_York
    tty: true
  scanner:
    image: kegtron-v1-api-proxy:dev
    depends_on:
      - api
    network_mode: host
    privileged: true
    environment:
      KENGTRON_SCANNER_PROXY_HOSTNAME: api
      KEGTRON_PROXY_ROLE: "scanner"
      TZ: America/New_York
    tty: true
      